### ISSUE TITLE
endianness is defined in reverse

### ISSUE THREAD

**Issue by solstice333** [SystemsApproach/book#63]
In data/presentation.rst ch7.1, we have this: 

> To make matters worse, on some machines integers are represented in big-endian form (the most significant bit of a word is in the byte with the highest address), while on other machines integers are represented in little-endian form (the most significant bit is in the byte with the lowest address).

This is phrased in reverse right? The way I understand endianness from OS, and what I just now had to reconfirm/review, big-endian means most significant byte is sent/stored first, and little-endian means least significant byte is sent/stored first, where "stored first" means the lower address, and "sent first" means first outgoing byte in a stream.

**Comment by drbruced12** [comment]
I believe you are right. I always have to look up endian-ness to confirm. Interestingly, that mistake has been there since the first edition, but we corrected the image (https://book.systemsapproach.org/data/presentation.html#id2) around the 3rd edition. So now the figure is out of sync with the text. I will make the fix, thank you!

**Comment by drbruced12** [comment]
Fixed in commit 83d06a1
