### ISSUE TITLE
Chapter 3.4 minor typo

### ISSUE THREAD

**Issue by mohammad-aliB** [SystemsApproach/book#74]
>  For example, we might decide that the maximum number of hops to get across a certain network is never going to be more than 16, and so we could pick 16 as the value that represents infinity. This at least bounds the amount of time that it takes to count to infinity. Of course, it could also present a problem if our network grew to a point where some nodes were separated by more than 16 hops.

I think the value that represents infinity should be 17 as in the first and last sentences it indicates the 16 is an acceptable number of hops.

**Comment by drbruced12** [comment]
No, we are simply pointing out that you could pick some arbitrary maximum hop count, and we use 16 as the example. We are not implying that 16 is sufficient - to the contrary we point out that it may prove insufficient. I'm not sure how we could be clearer.

**Comment by mohammad-aliB** [comment]
If the maximum hop count is 16. Shouldn't the value that represents infinity be at least 17?

**Comment by drbruced12** [comment]
Not really, no. But I have re-read the whole section and I think I see why it is confusing. The reason we set the value of infinity to something fairly small is so that the count-to-infinity problem gets addressed in bounded time. This means we can never discover a path that actually has 17 hops, but we already agree that this can't happen by design. But it could happen that a routing table would have values of 16 which in same cases mean that there was no route to a destination (i.e. infinite cost), and in some cases it would mean that the destination was 16 hops away. For the purposes of our example, this doesn't matter, but in some implementations it could mean that a real 16 hop path might never be discovered.  I think I will make a change (saying that our maximum network size is 15) so that future readers don't suffer from the same confusion. Thanks for your comments.
